---


- hosts: all
  become: true
  tasks:


  - name: update repository index
    yum:
     update_cache=yes


  - name: install apache2 package
    yum:
      name: httpd


  - name: add php support for apache
    yum:
      name: libapache2-mod-php
